### ISSUE TITLE
Add support for openid connect

### ISSUE THREAD

**Issue by lrabiet** [pac4j/lagom-pac4j#19]
openid connect won't work.

**Comment by ihostage** [comment]
Lagom is not a web framework, it's a framework for microservices.
I haven't an idea, how to implement `IndirectClient` for Lagom and I think that it's not an idiomatic way for Lagom, because:
1. Lagom haven't a session store like Play
2. Lagom is protocol agnostic and not support cookie (at least explicitly), but the cookie is the only way store state for `IndirectClient`.

But maybe you have an idea, how it can be implemented?

But the way, I don't think that `lagom-pac4j` not support OpenID Connect at all. For our projects, we use OpenID Connect (Keycloak) and all fine 😄 
We export JWK from OpenID Connect Provider and use `DirectClient` (see recipe https://github.com/lagom/lagom-recipes/pull/57).
Our formula:
`HeaderClient` + `JwtAuthenticator` + `CustomProfileExtractor` = support `OpenID Connect`
