### ISSUE TITLE
LagomWebContext not supported

### ISSUE THREAD

**Issue by akahanek** [pac4j/lagom-pac4j#26]
Most of the LagomWebContext class methods throw TechnicalException("Operation not supported"). 

The FacebookClient or TwitterClient call the ctx.getRequestParameter method during initialiation which throws mentioned exception in Lagom. It means, that I am not able to use these two clients in a Lagom application. 

Or am I doing something wrong?

Thank you.

**Comment by ihostage** [comment]
@akahanek `FacebookClient ` and  `TwitterClient` is a `IndirectClient`s. But Lagom is not a Web Framework like Play with support cookies and sessions. Pac4j Lagom support only `DirectClient`s. If you have an idea, how Pac4j Lagom can support `IndirectClient`s, please share her 😉 

PS: You can use a JWTClient (see examples) as partially support Facebook or Twitter. On our projects, we use an OpenID Connect for authentication/authorization, but on Lagom services, we use direct `JWTClient` instead of indirect `OpenIDClient`.


Regards,
Sergey

**Comment by akahanek** [comment]
Thank you for your hints :-)
